export const ROUTES = {
  IN_APP: {
    DASHQARDS: '/dashqards',
    AUTH: {
      LOGIN: '/auth/login',
      REGISTER: '/auth/register',
      RESET_PASSWORD: '/auth/reset-password',
      CREATE_PASSWORD: '/auth/create-password',
      OTP_VERIFICATION: '/auth/otp-verification',
    },
    DASHBOARD: {
      HOME: '/dashboard',
      CORPORATE: {
        HOME: '/dashboard/corporate',
        MANAGEMENT: '/dashboard/corporate/management',
        REQUESTS: '/dashboard/corporate/requests',
        PURCHASE: '/dashboard/corporate/purchase',
        TRANSACTIONS: '/dashboard/corporate/transactions',
        AUDIT_LOGS: '/dashboard/corporate/audit-logs',
        ADMINS: '/dashboard/corporate/admins',
        NOTIFICATIONS: '/dashboard/corporate/notifications',
        RECIPIENTS: '/dashboard/corporate/recipients',
        SETTINGS: '/dashboard/corporate/settings',
        COMPLIANCE: {
          ROOT: '/dashboard/corporate/compliance',
          PROFILE_INFORMATION: '/dashboard/corporate/compliance/profile',
          UPLOAD_ID: '/dashboard/corporate/compliance/upload-id',
          BUSINESS_DETAILS: '/dashboard/corporate/compliance/business-details',
          BUSINESS_IDENTIFICATION_CARDS:
            '/dashboard/corporate/compliance/business-identification-cards',
        },
      },
      VENDOR: {
        HOME: '/dashboard/vendor',
        EXPERIENCE: '/dashboard/vendor/experience',
        BRANCHES: '/dashboard/vendor/branches',
        REDEMPTIONS: '/dashboard/vendor/redemptions',
        REQUESTS: '/dashboard/vendor/requests',
        AUDIT_LOGS: '/dashboard/vendor/audit-logs',
        PAYMENT_METHODS: '/dashboard/vendor/payment-methods',
        PAYMENTS: '/dashboard/vendor/payments',
        INVITE_BRANCH_MANAGER: '/dashboard/vendor/invite-branch-manager',
        INVITE_ADMIN: '/dashboard/vendor/invite-admin',
        BRANCH_MANAGERS: '/dashboard/vendor/branch-managers',
        COMPLIANCE: {
          ROOT: '/dashboard/vendor/compliance',
          PROFILE_INFORMATION: '/dashboard/vendor/compliance/profile',
          UPLOAD_ID: '/dashboard/vendor/compliance/upload-id',
          BUSINESS_DETAILS: '/dashboard/vendor/compliance/business-details',
        },
        SETTINGS: '/dashboard/vendor/settings',
      },
      SETTINGS: {
        ROOT: '/dashboard/settings',
        PERSONAL_INFORMATION: '/dashboard/settings/personal-information',
        SECURITY_SETTINGS: '/dashboard/settings/security',
        PAYOUT_ACCOUNTS: '/dashboard/settings/payout-accounts',
      },
      GIFT_CARDS: {
        ROOT: '/dashboard/gift-cards',
        GIFT_CARD_DETAILS: '/dashboard/gift-cards/:id',
      },
      MY_CARDS: '/dashboard/my-cards',
      ORDERS: '/dashboard/orders',
      REDEEM: '/dashboard/redeem/dashpro',
      REDEMPTIONS: '/dashboard/redemptions',
      RECIPIENTS: '/dashboard/recipients',
      TRANSACTIONS: '/dashboard/transactions',
      COMPLIANCE: {
        ROOT: '/dashboard/compliance',
        PROFILE_INFORMATION: '/dashboard/compliance/profile',
        UPLOAD_ID: '/dashboard/compliance/upload-id',
        BUSINESS_DETAILS: '/dashboard/compliance/business-details',
        BUSINESS_IDENTIFICATION_CARDS: '/dashboard/compliance/business-identification-cards',
        ADD_BRANCH: '/dashboard/compliance/add-branch',
        CREATE_BRANCH: '/dashboard/compliance/add-branch/create',
      },
    },
    HOME: '/',
    ABOUT: '/about',
    GIFT_CARDS: '/gift-cards',
    SEARCH_CARDS: 'dashqards',
    CONTACT: '/contact',
    FAQ: '/faq',
    PURCHASE: '/purchase',
    REDEEM: '/redeem',
    LOGIN: '/login',
    SIGNUP: '/signup',
    VENDORS: '/vendors',
    CHECKOUT: '/checkout',
    TESTIMONIALS: '/testimonials',
    BULK_GIFTING: '/bulk-gifting',
    CORPORATE_SOLUTIONS: '/corporate-solutions',
    API_INTEGRATION: '/api-integration',
    TERMS_OF_SERVICE: '/terms-of-service',
    PRIVACY_POLICY: '/privacy-policy',
    COOKIE_POLICY: '/cookie-policy',
  },
  ENDPOINT: {
    ADMIN: {
      ROOT: '/admin',
      ARCHIVED: '/admin/archived',
      ROLES: '/admin/roles',
      PROFILE: '/admin/profile',
      ASSIGN_ROLES: '/admin/roles/admins',
      INVITE: '/admin/invite',
      BULK_INVITE: '/admin/bulk-invite',
      EDIT: '/admin/update/profile',
    },
    CUSTOMER: {
      ROOT: '/admin/customers',
      TRANSACTIONS: '/admin/transactions',
      DAILY_LIMIT: '/admin/transactions/pending-limits',
    },
    AGENT: {
      ROOT: '/admin/customers',
      TRANSACTIONS: '/admin/transactions',
    },
    MERCHANT: {
      ROOT: '/admin/customers',
      TRANSACTIONS: '/admin/transactions',
      DAILY_LIMIT: '/admin/transactions/pending-limits',
    },
  },
  EXTERNAL: {},
}

export const ENVIRONMENT = import.meta.env.VITE_NODE_ENV as string

const API_URLS: { [key: string]: string } = {
  development: import.meta.env.VITE_DEVELOPMENT_BASE_URL,
  staging: import.meta.env.VITE_STAGING_BASE_URL,
  production: import.meta.env.VITE_PRODUCTION_BASE_URL,
}

export const ENV_VARS = {
  API_BASE_URL: API_URLS[ENVIRONMENT] || API_URLS.development,
}

export const isTesting = ENVIRONMENT === 'test'

export const DEFAULT_QUERY = {
  limit: 10,
  after: '',
  status: '',
  search: '',
  card_type: '',
  phone_number: '',
  vendor_id: '',
  dateFrom: '',
  dateTo: '',
  location: '',
  branch: '',
}

export const MODAL_NAMES = {
  RECIPIENT: {
    ROOT: 'recipient-modal',
    ASSIGN: 'assign-recipient',
    BULK_UPLOAD: 'bulk-upload-recipient',
    CREATE: 'create-recipient',
  },
  AUTH: {
    ROOT: 'auth-modal',
    LOGOUT: 'logout',
  },
  ROLE: {
    ROOT: 'role-modal',
    CREATE: 'create-role',
    EDIT: 'edit-role',
    SELECT_PERMISSIONS: 'select-permissions',
    EDIT_PERMISSIONS: 'edit-permissions',
    ASSIGN_USER: 'assign-user',
    REASSIGN_ADMINS: 'reassign-admins',
    DELETE: 'delete-role',
    TOGGLE: 'toggle-role',
    REASSIGN_ADMINS_PROMPT: 'reassign-admins-prompt',
  },
  ADMIN: {
    ROOT: 'admin-modal',
    EDIT_ADMIN_ROLE: 'edit-admin-role',
    VIEW: 'view-admin',
    CREATE: 'invite-admin',
    BULK_INVITE: 'bulk-invite-admin',
    BULK_INVITE_PREVIEW: 'bulk-invite-admin-preview',
    EDIT: 'edit-admin',
    REMOVE: 'delete-admin',
    TOGGLE_STATUS: 'toggle-admin-status',
    RESEND_INVITE: 'resend-admin-invite',
    RESTORE: 'restore-admin',
    PERMANENTLY_DELETE: 'permanently-delete-admin',
  },
  CUSTOMER: {
    ROOT: 'customer-modal',
    VIEW: 'view-customer',
    DEACTIVATE: 'deactivate-customer',
    ACTIVATE: 'activate-customer',
    FREEZE: 'freeze-wallet',
    UNFREEZE: 'unfreeze-wallet',
    DELETE: 'delete-customer',
    APPROVE_KYC: 'approve-kyc',
    REJECT_KYC: 'reject-kyc',
    VIEW_KYC: 'view-customer-kyc',
    VIEW_KYC_DOCUMENT: 'view-customer-kyc-document',
    CREATE: 'create-customer',
    UPDATE: 'update-customer-profile',
    VIEW_GUARANTOR: 'view-customer-guarantor',
    TRANSACTIONS: 'customer-transactions',
    APPROVE_DAILY_LIMIT: 'approve-daily-limit',
    REJECT_DAILY_LIMIT: 'reject-daily-limit',
  },
  AGENT: {
    ROOT: 'agent-modal',
    VIEW: 'view-agent',
    DEACTIVATE: 'deactivate-agent',
    ACTIVATE: 'activate-agent',
    FREEZE: 'freeze-wallet',
    UNFREEZE: 'unfreeze-wallet',
    DELETE: 'delete-agent',
    BUSINESS_INFORMATION: 'business-information',
    VIEW_KYC: 'view-agent-kyc',
    VIEW_KYC_DOCUMENT: 'view-agent-kyc-document',
    UPDATE: 'update-agent-profile',
    TRANSACTIONS: 'agent-transactions',
    VIEW_GUARANTOR: 'view-agent-guarantor',
    APPROVE_KYC: 'approve-kyc',
    REJECT_KYC: 'reject-kyc',
  },
  MERCHANT: {
    ROOT: 'merchant-modal',
    VIEW: 'view-merchant',
    DEACTIVATE: 'deactivate-merchant',
    ACTIVATE: 'activate-merchant',
    FREEZE: 'freeze-wallet',
    UNFREEZE: 'unfreeze-wallet',
    DELETE: 'delete-merchant',
    BUSINESS_INFORMATION: 'business-information',
    VIEW_KYC: 'view-merchant-kyc',
    UPDATE: 'update-merchant-profile',
    TRANSACTIONS: 'merchant-transactions',
    VIEW_KYC_DOCUMENT: 'view-kyc-document',
    APPROVE_DAILY_LIMIT: 'approve-daily-limit',
    APPROVE_KYC: 'approve-kyc',
    REJECT_KYC: 'reject-kyc',
    REJECT_DAILY_LIMIT: 'reject-daily-limit',
  },
}
